v-sns/config/routes.rb
VSns::Application.routes.draw do
  get "comments/create"
  get "comments/destroy"
  devise_for :users, controllers: { confirmations: "confirmations" } 
  resources :posts do
     resources :comments
  end

  root 'welcome#index'

  

end

v-sns/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
	belongs_to :user
  #attr_accessible :body
end

v-sns/app/models/post.rb
class Post < ActiveRecord::Base
	# 유저가 지워지면 게시물도 다 같이 지워진다.
  belongs_to :user
  has_many :comments, :dependent => :destroy

	# accepts_nested_attributes_for :tags, :allow_destroy => :true,
  #   :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  mount_uploader :image, ImageUploader  

  acts_as_taggable_on :tags
end

v-sns/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

v-sns/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  belongs_to :role
  before_create :set_default_role
  has_many :posts
	has_many :comments
  
  devise :database_authenticatable, :registerable, :confirmable,
  :recoverable, :rememberable, :trackable, :validatable

  private
  def set_default_role
  	self.role ||= Role.find_by_name('registerd')
  end
end

v-sns/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

v-sns/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:body))
		@comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'show' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
		end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

		@post = Post.find(params[:post_id])
    
		respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
		end
  end 
end

v-sns/app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
	
  # POST /resource/confirmation
  def create
    # self.resource = resource_class.send_confirmation_instructions(resource_params)
    self.resource = resource_class.send_confirmation_instructions({email: current_user.email})
    if successfully_sent?(resource)
      respond_with({}, :location => after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    root_path
  end
end

v-sns/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :get_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]  
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    # 해당 유저의 포스트만 가져옴
      @posts = @user.posts
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # 유저와 Follow관계가 맺어있는 사람의 게시물을 가져와야합니다.
    
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
		
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      # @post = Post.find(params[:id])
      @post = @user.posts.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :image, :tag_list)
    end

    # 현재 유저 정보 가져옴
    def get_user
      @user = current_user || User.new
    end

  end

v-sns/app/controllers/registraions_controller.rb
class RegistraionsController < Devise::RegistrationsController
	protected

	def after_inactive_sign_up_path_for(resource)
    'user_confirmable_path'
  end
end

v-sns/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

v-sns/app/helpers/application_helper.rb
module ApplicationHelper
end

v-sns/app/helpers/comments_helper.rb
module CommentsHelper
end

v-sns/app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

v-sns/app/helpers/posts_helper.rb
module PostsHelper
	def join_tags(post)
    	post.tags.map { |t| t.name }.join(", ")
	end
end

v-sns/app/helpers/registraions_helper.rb
module RegistraionsHelper
end

v-sns/app/helpers/welcome_helper.rb
module WelcomeHelper
end

v-sns/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.email %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<% if signed_in? and comment.user == current_user %>	
	<p>
		<%= link_to 'Destroy Comment', [comment.post, comment],
								 :confirm => 'Are you sure?',
								 :method => :delete %>
	</p>
<% end %>

v-sns/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="control-group">
    <%= f.label :commenter, :class => 'control-label' %> 
    <div class="controls">
    	<%= f.text_field :commenter, value: current_user.email, readonly: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
    	<%= f.text_area :body %>
    </div> 
  </div>
  <div class="control-group">
  	<div class="controls">
			<%= f.submit class: 'btn' %>
  	</div>
  </div>
<% end %>

v-sns/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

v-sns/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

v-sns/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VSns</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="#">De.Chemist</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="active">
							<%= link_to 'Home', root_path %>
						</li>
						<li>
							<%= link_to 'Posts', posts_path %>
						</li>
                        <li><a href="../chatroom/web/index.html">Chatting Room</a></li>
						<li><a href="#about">About</a></li>
						<!-- <li><a href="#contact">Contact</a></li> -->
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="#">Action</a></li>
									<li><a href="#">Another action</a></li>
									<li><a href="#">Something else here</a></li>
									<li class="divider"></li>
									<li class="nav-header">Nav header</li>
									<li><a href="#">Separated link</a></li>
									<li><a href="#">One more separated link</a></li>
								</ul>
						</li>
					</ul>
					<form class="navbar-form pull-right">
						<!--
						<input class="span2" type="text" placeholder="Email">
						<input class="span2" type="password" placeholder="Password">
						-->
						<% if user_signed_in? %>
							Logged in as <strong><%= current_user.email %></strong>.
							<%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn' %>
							<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn'  %>
						<% else %>
							<%= link_to "Sign up", new_user_registration_path, :class => 'btn'  %>
							<%= link_to "Login", new_user_session_path, :class => 'btn'  %>
						<% end %>	
					</form>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span9">
				<% if notice %>
					<p class="alert alert-notice"><%= notice %></p>
				<% end %>
				<% if alert %>
					<p class="alert alert-error"><%= alert %></p>
				<% end %>
				<%= yield %>
			</div><!--/span-->
			<div class="span3">
				<div class="well sidebar-nav">
					<ul class="nav nav-list">
						<% if user_signed_in? %>
							<li class="nav-header"><%= current_user.email %></li>
							<%= gravatar_image_tag(current_user.email.gsub('spam', 'mdeering'), :alt => current_user.email ) %>
						<% end %>
						<li>Tags</li>
						<li>Followes</li>
						<li>Following</li>
						<li>Chat</li>
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
		</div><!--/row-->
	</div><!-- /container -->
</body>
</html>

v-sns/app/views/posts/_form.html.erb
<%= form_for(@post,html: {:class => "form-horizontal"}) do |f| %>
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="control-group">
  <%= f.label :title, :class => 'control-label' %> 
  <div class="controls">
    <%= f.text_field :title %>
  </div>
</div>  
<div class="control-group">
  <%= f.label :content, :class => 'control-label' %> 
  <div class="controls">
    <%= f.text_area :content %>
  </div>
</div>  
<div class="control-group">
  <%= f.label :image, :class => 'control-label' %> 
  <div class="controls">
    <%= f.file_field :image %>
  </div>
</div>  

<div class="control-group">
  <%= f.label :tag_list, :class => 'control-label' %> 
  <div class="controls">
    <%= f.text_field :tag_list %>
  </div>
</div>  

<div class="control-group">
  <div class="controls">
    <%= f.submit :class => 'btn' %>
  </div>
</div>
<% end %>

v-sns/app/views/posts/_post.html.erb
<li class="span4">
	<div class="thumbnail">
		<%= image_tag post.image_url %>
		<h3><%= post.title %></h3>
		<p><%= post.content %></p>
		<p><%= post.user.email %></p>
		<% if signed_in? and post.user == current_user %>	
		<p>
			<%= link_to 'Show', post_path(post), class: 'btn' %>
			<%= link_to 'Edit', edit_post_path(post), class: 'btn' %> 
			<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
		</p>
		<% end %>

	</div>
</li>

v-sns/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

v-sns/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<ul class="thumbnails">
	<%= render @posts %>
</ul>

<br>

<%= link_to 'New Post', new_post_path %>

v-sns/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

v-sns/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @post.title %>
</p>

<p>
	<strong>Content:</strong>
	<%= @post.content %>
</p>

<p>		
	<%= image_tag @post.image_url %>
</p>

<p>
	TAGS : <%= @post.tag_list %>
</p>

<%= render @post.comments %>
 
<% if user_signed_in? %>
	<%= render "comments/form" %>
<% end %>

<% if signed_in? and @post.user == current_user %>	
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

v-sns/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
	<%= link_to "Sign in", new_session_path(resource_name), :class => "btn" %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), :class => "btn" %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), :class => "btn" %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), :class => "btn" %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), :class => "btn" %>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider), :class => "btn" %>
  <% end -%>
<% end -%>

v-sns/app/views/welcome/index.html.erb
<div class="hero-unit">
	<h1>Hello, world!</h1>
	<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
</div>